### ISSUE TITLE
Write python code to analyze text

### ISSUE THREAD

**Issue by matiasandina** [amchagas/open-hardware-supply#2]
1. Explore shared code
1. Decide what is useful 
1. Implement what's lacking
1. Tabulate according to keywords (coarse filter)
1. Manual check to see whether the filter is good
1. Data analysis

**Comment by matiasandina** [comment]
After a brief look at the code, there are 2 scripts that can be useful `pdf_controller.py` and `models.py`.
If we get papers in .pdf format, we can parse them using pdf_controller, looks like functions to retrieve keywords (see #3 ) and tabulate have to be written by us.

**Comment by amchagas** [comment]
the dataset we have and how we deal with it have changed quite a bit. I am closing this issue as it seems no longer relevant
